name: liblab

services:
  postgres:
    image: postgres:15
    container_name: liblab-postgres
    environment:
      POSTGRES_DB: liblab
      POSTGRES_USER: liblab
      POSTGRES_PASSWORD: liblab_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U liblab -d liblab']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
