name: 💡 Feature Request
description: Suggest a new feature or enhancement for liblab.ai
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Your ideas help make liblab.ai better.

        Before submitting, please:
        1. Search existing issues to avoid duplicates
        2. Check our [roadmap](https://github.com/liblaber/ai/milestones) to see if it's already planned
        3. Consider how this fits with our project goals

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: Describe the problem or need this feature would address.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your ideal solution to the problem.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches have you considered?
      placeholder: Describe any alternative solutions or workarounds you've considered.
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - AI Integration & Capabilities
        - Developer Experience
        - Platform Reliability & Performance
        - Ecosystem Integration
        - Community & Collaboration
        - Documentation
        - Other (specify below)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Critical for adoption
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe how you would use this feature.
      placeholder: Walk us through a typical scenario where you'd use this feature.
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: How would this feature benefit the community?
      placeholder: Who else might benefit from this feature and how?
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas about how this could be implemented?
      placeholder: Share any technical thoughts or suggestions (optional).
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: Include any mockups, examples, or references that help illustrate your idea.
      placeholder: Drag and drop images here or provide links to examples.
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information that would be helpful.
      placeholder: Add any other context, links, or information here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests that might be similar
          required: true
        - label: I have checked the project roadmap for related features
          required: true
        - label: I am willing to contribute to the implementation if possible
          required: false
        - label: I am willing to help test this feature when it's implemented
          required: false
