echo ""
echo "        ┬  ┬┌┐ ┬  ┌─┐┌┐   ┌─┐┬"
echo "        │  │├┴┐│  ├─┤├┴┐  ├─┤│"
echo "        ┴─┘┴└─┘┴─┘┴ ┴└─┘  ┴ ┴┴"
echo ""
echo "Your liblab AI is live on \033[1;32mhttp://localhost:3000\033[0m 🎉"
echo ""
