echo ""
echo "        ┬  ┬┌┐ ┬  ┌─┐┌┐   ┌─┐┬"
echo "        │  │├┴┐│  ├─┤├┴┐  ├─┤│"
echo "        ┴─┘┴└─┘┴─┘┴ ┴└─┘  ┴ ┴┴"
echo ""
echo "Your liblab AI is building."
echo ""
echo "It will be available soon at \033[1;32mhttp://localhost:3000\033[0m"
echo ""
